"""Service functions for fetching and transforming market data."""

from market_data_engine.services.calculations import (
    CalculationError,
    annualized_volatility,
    bar_dates,
    comparable_price,
    log_returns,
    log_returns_from_bars,
    price_series,
    rolling_mean,
    rolling_mean_from_bars,
    rolling_volatility,
    rolling_volatility_from_bars,
    simple_returns,
    simple_returns_from_bars,
)
from market_data_engine.services.data_quality import (
    assess_data_quality,
    build_data_quality_report,
    build_data_quality_reports,
    collect_validation_errors,
    find_duplicate_dates,
    find_outlier_dates,
    find_stale_dates,
)
from market_data_engine.services.price_fetcher import (
    FetchResult,
    PriceFetcher,
    PriceRepositoryLike,
)
from market_data_engine.services.validation import (
    PriceValidationError,
    find_duplicate_bars,
    find_missing_weekdays,
    find_missing_weekdays_by_asset,
    iter_weekdays,
    validate_bars,
    validate_missing_weekdays,
    validate_price_bar,
)

__all__ = [
    "CalculationError",
    "FetchResult",
    "PriceFetcher",
    "PriceRepositoryLike",
    "PriceValidationError",
    "annualized_volatility",
    "assess_data_quality",
    "bar_dates",
    "build_data_quality_report",
    "build_data_quality_reports",
    "collect_validation_errors",
    "comparable_price",
    "find_duplicate_bars",
    "find_duplicate_dates",
    "find_missing_weekdays",
    "find_missing_weekdays_by_asset",
    "find_outlier_dates",
    "find_stale_dates",
    "iter_weekdays",
    "log_returns",
    "log_returns_from_bars",
    "price_series",
    "rolling_mean",
    "rolling_mean_from_bars",
    "rolling_volatility",
    "rolling_volatility_from_bars",
    "simple_returns",
    "simple_returns_from_bars",
    "validate_bars",
    "validate_missing_weekdays",
    "validate_price_bar",
]
